// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvMHkv9ryq9GgTKPmKuooADx7bzscjrHo',
    appId: '1:133272037828:web:43f61ced001eaff925dc91',
    messagingSenderId: '133272037828',
    projectId: 'fir-crud-aefa1',
    authDomain: 'fir-crud-aefa1.firebaseapp.com',
    storageBucket: 'fir-crud-aefa1.firebasestorage.app',
    measurementId: 'G-4Q2EKRMQH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzTcMdnOxsAaqPtJtLTEUVGbLgGJsYyko',
    appId: '1:133272037828:android:c445c5f08b5e0da525dc91',
    messagingSenderId: '133272037828',
    projectId: 'fir-crud-aefa1',
    storageBucket: 'fir-crud-aefa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARLJrTmcsr3ewXQHX3VI1vrd8F8ql_ZSo',
    appId: '1:133272037828:ios:0a797fade3ae2e1025dc91',
    messagingSenderId: '133272037828',
    projectId: 'fir-crud-aefa1',
    storageBucket: 'fir-crud-aefa1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARLJrTmcsr3ewXQHX3VI1vrd8F8ql_ZSo',
    appId: '1:133272037828:ios:0a797fade3ae2e1025dc91',
    messagingSenderId: '133272037828',
    projectId: 'fir-crud-aefa1',
    storageBucket: 'fir-crud-aefa1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvMHkv9ryq9GgTKPmKuooADx7bzscjrHo',
    appId: '1:133272037828:web:393f834b6b9ce64825dc91',
    messagingSenderId: '133272037828',
    projectId: 'fir-crud-aefa1',
    authDomain: 'fir-crud-aefa1.firebaseapp.com',
    storageBucket: 'fir-crud-aefa1.firebasestorage.app',
    measurementId: 'G-ZNEK8QYMCZ',
  );

}